"""empty message

Revision ID: 53367049da1b
Revises: c624d2bc48d3
Create Date: 2023-06-28 16:10:19.329168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53367049da1b'
down_revision = 'c624d2bc48d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pieza', sa.String(length=20), nullable=True),
    sa.Column('cantidad', sa.String(length=8), nullable=True),
    sa.Column('imagen', sa.String(length=200), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('detalle_piezas_pedidos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_piezas_pedidos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pieza', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cantidad', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('imagen', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('pedido_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name='detalle_piezas_pedidos_pedido_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='detalle_piezas_pedidos_pkey')
    )
    op.drop_table('detalle')
    # ### end Alembic commands ###
