"""empty message

Revision ID: 6a71596c5ab1
Revises: b5d2cf724d28
Create Date: 2023-06-26 20:21:53.975479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a71596c5ab1'
down_revision = 'b5d2cf724d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=20), nullable=True),
    sa.Column('marca', sa.String(length=80), nullable=True),
    sa.Column('año', sa.Integer(), nullable=True),
    sa.Column('serial', sa.String(length=20), nullable=True),
    sa.Column('piezas', sa.String(length=200), nullable=True),
    sa.Column('cantidad', sa.String(length=8), nullable=True),
    sa.Column('imagen', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cedula', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('direccion', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('nombre_completo', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('tipo', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('salt', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['cedula'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('salt')
        batch_op.drop_column('tipo')
        batch_op.drop_column('nombre_completo')
        batch_op.drop_column('direccion')
        batch_op.drop_column('cedula')

    op.drop_table('pedidos')
    # ### end Alembic commands ###
