"""empty message

Revision ID: c624d2bc48d3
Revises: 9e1aeec9564c
Create Date: 2023-06-28 15:57:43.674532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c624d2bc48d3'
down_revision = '9e1aeec9564c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_piezas_pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pieza', sa.String(length=20), nullable=True),
    sa.Column('cantidad', sa.String(length=8), nullable=True),
    sa.Column('imagen', sa.String(length=200), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('piezas')
        batch_op.drop_column('imagen')
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('imagen', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('piezas', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    op.drop_table('detalle_piezas_pedidos')
    # ### end Alembic commands ###
